name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Сборка запускается при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/botpress2:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/botpress2:latest

    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Tag Docker image for GitHub Packages
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/botpress2:latest ghcr.io/${{ secrets.DOCKER_USERNAME }}/botpress2:latest

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/botpress2:latest
